---
version: "3"

tasks:
  main:
    desc: main account
    cmds:
      - protontricks -c 'wine injector.exe' 4240740151

  steam:
    desc: steam account
    cmds:
      - protontricks -c 'wine injector.exe' 550470
  logs:
    desc: logs
    cmds:
      - tail -f /home/derp/.steam/steam/steamapps/compatdata/4240740151/pfx/drive_c/Nostale/payload_debug.log

  sent:
    desc: sent logs
    cmds:
      - tail -f /home/derp/.steam/steam/steamapps/compatdata/4240740151/pfx/drive_c/Nostale/payload_sent_packets.log

  clean:
    desc: clean up
    cmds:
      - rm *.obj
